var Pepyaka = {
    o: {
        fontsPath: '/fonts/',
        domain: 'pepyaka.su',
        path: ''
    },

    markups: {
        html: {
            link: '<a href="{{href}}">{{text}}</a>',
            img: '<img src="{{src}}" alt="{{alt}}">'
        },
        bb: {
            link: '[URL={{href}}]{{text}}[/URL]',
            img: '[IMG]{{src}}[/IMG]'
        },
        md: {
            img: '![{{alt}}]({{src}})'
        },
        beon: {
            img: '[image-original-none-{{src}}]'
        }
    },

    imgData: {
        cron: {
            ' ': 'space',
            'ё': 'E',
            'а': 'A',
            'б': 'B',
            'в': 'V',
            'г': 'G',
            'д': 'D',
            'е': 'E',
            'ж': 'ZH',
            'з': 'Z',
            'и': 'I',
            'й': 'J',
            'к': 'K',
            'л': 'L',
            'м': 'M',
            'н': 'N',
            'о': 'O',
            'п': 'P',
            'р': 'R',
            'с': 'S',
            'т': 'T',
            'у': 'U',
            'ф': 'F',
            'х': 'X',
            'ц': 'TS',
            'ч': 'CH',
            'ш': 'SH',
            'щ': 'SHJ',
            'ъ': 'TZ',
            'ы': 'II',
            'ь': 'MZ',
            'э': 'EE',
            'ю': 'JU',
            'я': 'YA'
        },
        hardcoreololo: {
            ' ': 'space',
            '!': 's0_1_1',
            '"': 's2_2_1',
            '$': 's0_4_1',
            '%': 's0_5_1',
            "'": 's0_0_1',
            '*': 's0_8_1',
            '+': 's0_12_1',
            ',': 's3_1_2',
            '-': 's0_11_2',
            '.': 's3_2_2',
            '/': 's3_3_2',
            '0': 's0_10_1',
            '1': 's0_1_2',
            '2': 's0_2_2',
            '3': 's0_3_2',
            '4': 's0_4_2',
            '5': 's0_5_2',
            '6': 's0_6_1',
            '7': 's0_7_1',
            '8': 's0_8_2',
            '9': 's0_9_1',
            ':': 's2_1_1',
            ';': 's2_1_2',
            '<': 's3_1_1',
            '=': 's0_12_2',
            '>': 's3_2_1',
            '?': 's3_3_1',
            '@': 's0_2_1',
            '[': 's1_1_1',
            '\\': 's0_13_1',
            ']': 's1_2_1',
            '_': 's0_11_1',
            'a': 'a',
            'b': 'dr',
            'c': 'c',
            'd': 'd',
            'e': 'tr',
            'f': 'f',
            'g': 'g',
            'h': 'yr',
            'i': 'i',
            'j': 'j',
            'k': 'rr',
            'l': 'l',
            'm': 'vr',
            'n': 'n',
            'o': 'o',
            'p': 'p',
            'q': 'q',
            'r': 'r',
            's': 's',
            't': 't',
            'u': 'u',
            'v': 'v',
            'w': 'w',
            'x': 's1_1_2',
            'y': 'y',
            'z': 'z',
            'ё': 's0_0_2',
            '№': 's0_3_1',
            'а': 'a',
            'б': 's3_1_3',
            'в': 'dr',
            'г': 'ur',
            'д': 'lr',
            'е': 'tr',
            'ж': 's2_1_3',
            'з': 'pr',
            'и': 'br',
            'й': 'qr',
            'к': 'rr',
            'л': 'kr',
            'м': 'vr',
            'н': 'yr',
            'о': 'o',
            'п': 'gr',
            'р': 'p',
            'с': 'c',
            'т': 't',
            'у': 'er',
            'ф': 'ar',
            'х': 's1_1_2',
            'ц': 'wr',
            'ч': 'xr',
            'ш': 'ir',
            'щ': 'or',
            'ъ': 's1_2_2',
            'ы': 'sr',
            'ь': 'mr',
            'э': 's2_2_2',
            'ю': 's3_2_3',
            'я': 'zr'
        },
        katjka: {
            ' ': 'empty',
            '!': 'voskl',
            '(': 'sk_lev',
            ')': 'sk_prav',
            '+': 'plus',
            ',': 'zpt',
            '-': 'min',
            '.': 'tck',
            '0': '0',
            '1': '1',
            '2': '2',
            '3': '3',
            '4': '4',
            '5': '5',
            '6': '6',
            '7': '7',
            '8': '8',
            '9': '9',
            ':': 'dvoetc',
            '?': 'vopr',
            'A': 'a',
            'B': 'b',
            'C': 'c',
            'D': 'd',
            'E': 'e',
            'F': 'f',
            'G': 'g',
            'H': 'h',
            'I': 'i',
            'J': 'j',
            'K': 'k',
            'L': 'l',
            'M': 'm',
            'N': 'n',
            'O': 'o',
            'P': 'p',
            'Q': 'q',
            'R': 'r',
            'S': 's',
            'T': 't',
            'U': 'u',
            'V': 'v',
            'W': 'w',
            'X': 'x',
            'Y': 'y',
            'Z': 'z',
            '[': 'kv_sk_lev',
            ']': 'kv_sk_prav',
            'Ё': 'D081',
            'ё': 'D191',
            'А': 'D090',
            'Б': 'D091',
            'В': 'D092',
            'Г': 'D093',
            'Д': 'D094',
            'Е': 'D095',
            'Ж': 'D096',
            'З': 'D097',
            'И': 'D098',
            'Й': 'D099',
            'К': 'D09A',
            'Л': 'D09B',
            'М': 'D09C',
            'Н': 'D09D',
            'О': 'D09E',
            'П': 'D09F',
            'Р': 'D0A0',
            'С': 'D0A1',
            'Т': 'D0A2',
            'У': 'D0A3',
            'Ф': 'D0A4',
            'Х': 'D0A5',
            'Ц': 'D0A6',
            'Ч': 'D0A7',
            'Ш': 'D0A8',
            'Щ': 'D0A9',
            'Э': 'D0AD',
            'Ю': 'D0AE',
            'Я': 'D0AF',
            'а': 'D0B0',
            'б': 'D0B1',
            'в': 'D0B2',
            'г': 'D0B3',
            'д': 'D0B4',
            'е': 'D0B5',
            'ж': 'D0B6',
            'з': 'D0B7',
            'и': 'D0B8',
            'й': 'D0B9',
            'к': 'D0BA',
            'л': 'D0BB',
            'м': 'D0BC',
            'н': 'D0BD',
            'о': 'D0BE',
            'п': 'D0BF',
            'р': 'D180',
            'с': 'D181',
            'т': 'D182',
            'у': 'D183',
            'ф': 'D184',
            'х': 'D185',
            'ц': 'D186',
            'ч': 'D187',
            'ш': 'D188',
            'щ': 'D189',
            'ъ': 'D18A',
            'ы': 'D18B',
            'ь': 'D18C',
            'э': 'D18D',
            'ю': 'D18E',
            'я': 'D18F'
        },
        lobster: {
            ' ': 'space',
            '!': 'zn_voskl',
            '"': 'zn_kavichka',
            '%': 'zn_percent',
            '(': 'zn_skobka_otkr',
            ')': 'zn_skobka_zakr',
            ',': 'zn_zapyataya',
            '-': 'zn_tire',
            '.': 'zn_tochka',
            '0': 'num_0',
            '1': 'num_1',
            '2': 'num_2',
            '3': 'num_3',
            '4': 'num_4',
            '5': 'num_5',
            '6': 'num_6',
            '7': 'num_7',
            '8': 'num_8',
            '9': 'num_9',
            ':': 'zn_dvoetochie',
            '<': 'zn_less',
            '>': 'zn_greater',
            '?': 'zn_vopr',
            'A': 'a',
            'B': 'b',
            'C': 'c',
            'D': 'd',
            'E': 'e',
            'F': 'f',
            'G': 'g',
            'H': 'h',
            'I': 'i',
            'J': 'j',
            'K': 'k',
            'L': 'l',
            'M': 'm',
            'N': 'n',
            'O': 'o',
            'P': 'p',
            'Q': 'q',
            'R': 'r',
            'S': 's',
            'T': 't',
            'U': 'u',
            'V': 'v',
            'W': 'w',
            'X': 'x',
            'Y': 'y',
            'Z': 'z',
            'Ё': 'rus_yo',
            'А': 'a',
            'Б': 'rus_be',
            'В': 'b',
            'Г': 'rus_ge',
            'Д': 'rus_de',
            'Е': 'e',
            'Ж': 'rus_je',
            'З': 'rus_ze',
            'И': 'rus_i',
            'Й': 'rus_i_kratkoe',
            'К': 'k',
            'Л': 'rus_el',
            'М': 'm',
            'Н': 'h',
            'О': 'o',
            'П': 'rus_pe',
            'Р': 'p',
            'С': 'c',
            'Т': 't',
            'У': 'rus_u',
            'Ф': 'rus_ef',
            'Х': 'x',
            'Ц': 'rus_ce',
            'Ч': 'rus_che',
            'Ш': 'rus_sha',
            'Щ': 'rus_shcha',
            'Ъ': 'rus_tv_zn',
            'Ы': 'rus_y',
            'Ь': 'rus_m_zn',
            'Э': 'rus_e_ob',
            'Ю': 'rus_yu',
            'Я': 'rus_ya'
        },
        wd: {
            ' ': 'space',
            '!': 'font2_89',
            '"': 'font3_11',
            '#': 'font4_17',
            '$': 'font4_43',
            '%': 'font4_54',
            '&': 'font4_20',
            '(': 'font2_107',
            ')': 'font2_110',
            '*': 'font4_23',
            '+': 'font4_14',
            ',': 'font2_95',
            '-': 'font4_05',
            '.': 'font2_105',
            '/': 'font4_49',
            '0': 'font3_30',
            '1': 'font3_08',
            '2': 'font3_03',
            '3': 'font3_17',
            '4': 'font3_05',
            '5': 'font3_14',
            '6': 'font3_26',
            '7': 'font3_28',
            '8': 'font3_38',
            '9': 'font3_35',
            ':': 'font2_98',
            ';': 'font4_25',
            '<': 'font4_46',
            '=': 'font4_11',
            '>': 'font4_40',
            '?': 'font2_92',
            '@': 'font3_32',
            '\\': 'font4_51',
            'a': 'font2_08',
            'b': 'font2_10',
            'c': 'font2_12',
            'd': 'font2_14',
            'e': 'font2_16',
            'f': 'font2_22',
            'g': 'font2_03',
            'h': 'font2_05',
            'i': 'font4_03',
            'j': 'font2_32',
            'k': 'font2_25',
            'l': 'font2_27',
            'm': 'font2_29',
            'n': 'n',
            'o': 'font2_19',
            'p': 'font2_55',
            'q': 'font2_75',
            'r': 'font2_58',
            's': 'font2_64',
            't': 'font2_66',
            'u': 'font2_48',
            'v': 'font2_52',
            'w': 'font2_50',
            'x': 'font2_61',
            'y': 'font2_72',
            'z': 'font2_69',
            '|': 'font4_60',
            '—': 'font4_57',
            '«': 'font2_100',
            'ё': 'font_39',
            '№': 'font4_37',
            '»': 'font2_102',
            'а': 'font_15',
            'б': 'font_17',
            'в': 'font_19',
            'г': 'font_06',
            'д': 'font_22',
            'е': 'font_24',
            'ж': 'font_08',
            'з': 'font_27',
            'и': 'font_10',
            'й': 'font4_08',
            'к': 'font_30',
            'л': 'font_12',
            'м': 'font2_29',
            'н': 'font_33',
            'о': 'font_45',
            'п': 'font_03',
            'р': 'font_36',
            'с': 'font_96',
            'т': 'font_68',
            'у': 'font_70',
            'ф': 'font_73',
            'х': 'font_99',
            'ц': 'font_76',
            'ч': 'font_78',
            'ш': 'font_80',
            'щ': 'font_82',
            'ъ': 'font_84',
            'ы': 'font_65',
            'ь': 'font_87',
            'э': 'font_89',
            'ю': 'font_91',
            'я': 'font_93'
        }
    },

    getGifs: function(text, fonts) {
        var _this = this,
            data = _this.imgData,
            resultArr = [],
            fonts = (fonts && fonts.length? fonts : ['cron', 'hardcoreololo', 'katjka', 'lobster', 'wd']);

        for (var i = 0, l = text.length - 1; i <= l; i++) {
            var variants = [],
                character = text[i];

            for (var j = fonts.length - 1; j >= 0; j--) {
                var font = fonts[j],
                    found;
                
                found = data[font][character] || data[font][character.toLowerCase()] || data[font][character.toUpperCase()];
                if (found) variants.push(_this.o.fontsPath + font + '/' + found + '.gif');            
            };

            if (variants.length) {
                resultArr.push([character, variants[Math.floor(Math.random()*variants.length)]]);
            }
            else {
                resultArr.push(undefined);
            }
        };

        return resultArr;
    },

    generateMarkup: function(arr, options) {
        var o = options || {};
        
        o.markupName = o.markupName || 'html';
        o.includeLink = o.includeLink || false;
        o.includeDomain = o.includeDomain || false;

        var _this = this,
            result = '',
            imgTemplate = _this.markups[o.markupName].img,
            linkTemplate = _this.markups[o.markupName].link,
            domain = (o.includeDomain? 'http://' + _this.o.domain: ''),
            escapeHtml = function(str) {
                return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
            };

        for (var i = 0, l = arr.length - 1; i <= l; i++) {
            if (arr[i]) result += imgTemplate.replace('{{src}}', domain + arr[i][1]).replace('{{alt}}', escapeHtml(arr[i][0]));
        }

        if (o.includeLink && linkTemplate) result = linkTemplate.replace('{{href}}', domain + '/' + _this.o.path).replace('{{text}}', result);

        return result;
    }
};
